library(ISLR)
library(MASS)
view(nyp_data)
fix(nyp_data)
names(nyp_data)
attach(nyp_data)
lm.fit=lm(Mean_Cost~APR_DRG_Code,data=nyp_data)
lm.fit=lm(Mean_Cost~APR_DRG_Code)
lm.fit
summary(lm.fit)
coef(lm.fit)
confint(lm.fit)
plot(APR_DRG_Code,Mean_Cost,col="blue")
abline(lm.fit,lwd=3)
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit),residuals(lm.fit))
plot(predict(lm.fit),rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))

lm.fit=lm(Mean_Cost~APR_DRG_Code+Discharges,data = nyp_data)
lm.fit=lm(Mean_Cost~.,data=nyp_data)
summary(lm.fit)
